const VERSION='0.3.3';
const AUTH_URL='https://www.scad.mx/com-autenticacion';
const CONTEXT_URL='https://www.scad.mx/_functions/comPwaContext';
const TVDI_HLS='https://motortv.scad.mx/hls/canal.m3u8';
const MEMBER_KEY='scad_com_member_id';

let context=null,tvMuted=true,hls=null,deferredInstallPrompt=null;
const $=id=>document.getElementById(id);
const modal=$('moduleModal'),modalTitle=$('modalTitle'),modalDescription=$('modalDescription'),modalContent=$('modalContent'),identityButton=$('identityButton'),identityMenu=$('identityMenu'),tvVideo=$('tvVideo'),tvPlaceholder=$('tvPlaceholder'),tvScreenCenter=$('tvScreenCenter');

function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function initials(name=''){return name.trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'US'}
function showModal(title,description='',html=''){modalTitle.textContent=title;modalDescription.textContent=description;modalContent.innerHTML=html;modal.hidden=false;document.body.style.overflow='hidden'}
function closeModal(){modal.hidden=true;document.body.style.overflow=''}
function getMemberId(){const p=new URLSearchParams(location.search);const incoming=String(p.get('memberId')||'').trim();if(incoming){localStorage.setItem(MEMBER_KEY,incoming);history.replaceState({},document.title,location.pathname);return incoming}return String(localStorage.getItem(MEMBER_KEY)||'').trim()}
function clearSession(){localStorage.removeItem(MEMBER_KEY);context=null}
function startLogin(){location.assign(AUTH_URL)}

async function loadContext(memberId){if(!memberId)return null;const url=`${CONTEXT_URL}?memberId=${encodeURIComponent(memberId)}`;const r=await fetch(url,{cache:'no-store'});const data=await r.json().catch(()=>({ok:false,mensaje:`HTTP ${r.status}`}));if(!r.ok||!data.ok)throw new Error(data.mensaje||`Contexto COM ${r.status}`);return data}

function renderIdentity(){const u=context.usuario,e=context.eo,name=u.nombreVisible||u.nombre||'Usuario',ini=initials(name);['identityAvatar','menuAvatar'].forEach(id=>$(id).textContent=ini);$('identityName').textContent=name;$('menuName').textContent=name;$('identityEO').textContent=e.nombreVisible||e.nombre;$('menuStatus').textContent='Miembro activo';$('communityName').textContent=e.nombreVisible||e.nombre;$('communityStatus').textContent='Miembro activo';$('communityLogo').textContent=initials(e.nombreVisible||e.nombre)}
function formatActivity(a){const d=new Date(a.inicio),day=String(d.getDate()).padStart(2,'0'),month=d.toLocaleDateString('es-MX',{month:'short'}).replace('.','').toUpperCase(),time=a.todoElDia?'TODO EL DÍA':d.toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'});return `<button class="event-row" data-activity="${esc(a.id)}" type="button"><time><strong>${day}</strong><span>${esc(month)}</span></time><span class="event-info"><small>${esc(time)} · ${esc(a.tipoActividad||'ACTIVIDAD')}</small><strong>${esc(a.titulo)}</strong><span>${esc(a.ubicacion||'')}</span></span><span class="row-arrow">›</span></button>`}
function renderAgenda(){const list=context.actividades||[];$('programacionMeta').textContent=list.length?`${list.length} próximas`:'Sin próximas';$('agendaTimeline').innerHTML=list.length?list.slice(0,3).map(formatActivity).join(''):'<div class="prototype-row"><strong>No hay próximas actividades.</strong></div>';$('agendaTimeline').querySelectorAll('[data-activity]').forEach(b=>b.onclick=()=>openActivity(list.find(x=>x.id===b.dataset.activity)))}
function renderStatus(){const docs=context.documentos||[];$('documentacionMeta').textContent=docs.length?`${docs.length} disponibles`:'Sin documentos';$('statusPanel').innerHTML=`<div class="prototype-row"><strong>Acceso</strong><span>Activo</span></div><div class="prototype-row"><strong>Comunidad</strong><span>${esc(context.eo.nombreVisible||context.eo.nombre)}</span></div><div class="prototype-row"><strong>Documentos</strong><span>${docs.length}</span></div>`}
function renderContext(){renderIdentity();renderAgenda();renderStatus();if($('tvChannelSelect').value==='comunidad')playCommunity()}

function openActivity(a){if(!a)return;showModal(a.titulo,a.descripcion||'',`<div class="prototype-row"><strong>Inicio</strong><span>${new Date(a.inicio).toLocaleString('es-MX')}</span></div>${a.fin?`<div class="prototype-row"><strong>Término</strong><span>${new Date(a.fin).toLocaleString('es-MX')}</span></div>`:''}${a.ubicacion?`<div class="prototype-row"><strong>Lugar</strong><span>${esc(a.ubicacion)}</span></div>`:''}${a.enlace?`<a class="prototype-row" href="${esc(a.enlace)}" target="_blank" rel="noopener"><strong>Abrir enlace</strong><span>↗</span></a>`:''}`)}
function openProgramacion(){const list=context?.actividades||[];showModal('Programación','',list.length?list.map(a=>`<button class="prototype-row activity-open" data-id="${esc(a.id)}" type="button"><strong>${esc(a.titulo)}</strong><span>${new Date(a.inicio).toLocaleString('es-MX')}</span></button>`).join(''):'<div class="prototype-row"><strong>No hay actividades próximas.</strong></div>');modalContent.querySelectorAll('.activity-open').forEach(b=>b.onclick=()=>openActivity(list.find(a=>a.id===b.dataset.id)))}
function openDocumentos(){const list=context?.documentos||[];showModal('Documentación','',list.length?list.map(d=>`<a class="prototype-row" href="${esc(d.documentoUrl)}" target="_blank" rel="noopener"><strong>${esc(d.titulo)}</strong><span>${esc(d.categoria||d.nombreArchivo||'Abrir')} ↗</span></a>`).join(''):'<div class="prototype-row"><strong>No hay documentos disponibles.</strong></div>')}
function openProfile(){const u=context?.usuario,e=context?.eo;if(!u)return;showModal('Mi perfil','',`<div class="profile-card"><span class="avatar">${initials(u.nombreVisible||u.nombre)}</span><div><strong>${esc(u.nombreVisible||u.nombre)}</strong><span>${esc(u.email||'')}</span></div></div><div class="prototype-row"><strong>Comunidad</strong><span>${esc(e.nombreVisible||e.nombre)}</span></div><div class="prototype-row"><strong>Roles</strong><span>${esc((u.roles||[]).join(' · '))}</span></div><div class="prototype-row"><strong>Estado</strong><span>Activo</span></div>`)}
function openCommunityInfo(){const e=context?.eo;if(!e)return;showModal(e.nombreVisible||e.nombre,'',`<div class="prototype-row"><strong>Código</strong><span>${esc(e.codigoEO||'')}</span></div><div class="prototype-row"><strong>Estado</strong><span>Activa</span></div>`)}
function openModule(key){if(!context)return;if(key==='programacion')return openProgramacion();if(key==='documentacion')return openDocumentos();if(key==='mensajeria')return showModal('Mensajería','MNS se integrará sobre el contexto APP + EO ya autenticado.','<div class="prototype-row"><strong>Estado</strong><span>Pendiente de interfaz MNS</span></div>');showModal('Capacitación','', '<div class="prototype-row"><strong>Estado</strong><span>Pendiente de integración</span></div>')}

function destroyHls(){if(hls){hls.destroy();hls=null}tvVideo.pause();tvVideo.removeAttribute('src');tvVideo.load()}
function setPlaceholder(active){tvPlaceholder.hidden=!active;tvScreenCenter.hidden=!active;tvVideo.hidden=active}
function playUrl(url){destroyHls();if(!url){setPlaceholder(true);return}setPlaceholder(false);tvVideo.muted=tvMuted;if(/\.m3u8($|\?)/i.test(url)){if(tvVideo.canPlayType('application/vnd.apple.mpegurl')){tvVideo.src=url;tvVideo.play().catch(()=>{});return}if(window.Hls&&Hls.isSupported()){hls=new Hls({enableWorker:true,lowLatencyMode:false,backBufferLength:30});hls.loadSource(url);hls.attachMedia(tvVideo);hls.on(Hls.Events.MANIFEST_PARSED,()=>tvVideo.play().catch(()=>{}));hls.on(Hls.Events.ERROR,(_,d)=>{if(d.fatal)setPlaceholder(true)});return}}tvVideo.src=url;tvVideo.play().catch(()=>{})}
function playCommunity(){const tv=context?.tv;if(!tv?.youtubeId){destroyHls();setPlaceholder(true);tvScreenCenter.innerHTML='<span class="tv-play">▶</span>';return}destroyHls();setPlaceholder(false);tvVideo.hidden=true;tvPlaceholder.hidden=false;tvScreenCenter.hidden=false;const start=Math.max(0,Math.floor(Number(tv.segundoInicio)||0));const base=tv.youtubeUrl||`https://www.youtube.com/watch?v=${tv.youtubeId}`;const join=base.includes('?')?'&':'?';tvScreenCenter.innerHTML=`<a href="${esc(`${base}${join}t=${start}s`)}" target="_blank" rel="noopener" class="tv-play" aria-label="Abrir Canal Comunidad">▶</a>`}
function setTvChannel(ch){$('tvScreen').dataset.channel=ch;if(ch==='tvdi')playUrl(TVDI_HLS);else playCommunity()}

function logout(){clearSession();location.assign(`${AUTH_URL}?logout=1`)}
function showAuthError(err){$('communityStatus').textContent='Acceso no disponible';$('agendaTimeline').innerHTML='<div class="prototype-row"><strong>No fue posible cargar la agenda.</strong></div>';$('statusPanel').innerHTML=`<div class="prototype-row"><strong>Acceso</strong><span>${esc(err.message||String(err))}</span></div>`;showModal('Acceso a SCaD Comunidad','No fue posible validar tu sesión.',`<div class="prototype-row"><strong>Detalle</strong><span>${esc(err.message||String(err))}</span></div><button class="install-button" id="retryLogin" type="button">Iniciar sesión</button>`);setTimeout(()=>{const b=$('retryLogin');if(b)b.onclick=startLogin},0)}

function wireUI(){$('modalClose').onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)closeModal()});identityButton.onclick=e=>{e.stopPropagation();identityMenu.hidden=!identityMenu.hidden;identityButton.setAttribute('aria-expanded',String(!identityMenu.hidden))};identityMenu.onclick=e=>e.stopPropagation();document.addEventListener('click',()=>{identityMenu.hidden=true;identityButton.setAttribute('aria-expanded','false')});document.querySelectorAll('[data-route="perfil"]').forEach(b=>b.onclick=()=>openProfile());document.querySelectorAll('[data-route="inicio"]').forEach(b=>b.onclick=()=>scrollTo({top:0,behavior:'smooth'}));document.querySelectorAll('[data-module]').forEach(b=>b.onclick=()=>openModule(b.dataset.module));$('communityInfoButton').onclick=openCommunityInfo;$('logoutButton').onclick=logout;$('tvChannelSelect').onchange=e=>setTvChannel(e.target.value);$('tvMuteButton').onclick=()=>{tvMuted=!tvMuted;tvVideo.muted=tvMuted;$('tvMuteIcon').textContent=tvMuted?'🔇':'🔊';if(!tvMuted)tvVideo.play().catch(()=>{})};$('tvFullscreenButton').onclick=async()=>{try{if(!document.fullscreenElement)await $('tvScreen').requestFullscreen();else await document.exitFullscreen()}catch{}}}
function setupInstall(){const b=$('installAppButton');const installed=()=>matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;const set=()=>{b.textContent='App instalada';b.disabled=true;b.classList.add('installed')};if(installed())set();addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;if(!installed()){b.textContent='Instalar app';b.disabled=false}});addEventListener('appinstalled',set);b.onclick=async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null}}}

async function boot(){wireUI();setupInstall();setTvChannel('tvdi');try{const memberId=getMemberId();if(!memberId){startLogin();return}context=await loadContext(memberId);renderContext()}catch(e){console.error('[SCaD COM]',e);showAuthError(e)}if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.error))}
boot();